* Fruit of Knowledge and the bodies of the Gods - Baniwa people - Robin Wright

1. What is the main origin story of the Baniwa people, and how does it
   connect to the environment?

   Main origin story is the felling of the tree - Kaali-ka thidzapa
   which connected the Other world of the deities with This world.
   ~Nhiãperikuli~, the creator walked on earth and made the things
   that prosper human life on earth overcoming obstacles that
   threatened his existence using his prophetic skills. ~Kuwai~, the
   son of ~Nhiãperikuli~, is the creator of all fruits and palms. All
   the earthly stuff comes from his excrements. He connects humans to
   environment in the creation story by burning himself in fire in
   response to concerns about food shortage for humans. ~Kaali~ is the
   creator of all cultivated plants. 

2. What is the origin story of parika, and how does it connect to
   their stories about the animals?

   ~Parika~ aka shaman's snuff came from the Great Tree of Kaali -
   ~Kaali-ka thidzapa~. When the tree was felled, the ~Parika~ was in
   an hole at the top of the tree. ~Nhiãperikuli~ tries to reach for
   it before a tapir gets hold of it. The act of the tapir in taking
   something that doesn't belong to it and consuming something that is
   not meant for it is related, in analogy, to that of a selfish and
   gluttonous Jaguar.

3. How do these origin stories explain the world? Give specific
   examples.

   1. Humans are deeply connected with the environment they live in.
      This is emphasized in the reverance for certain plants, that are
      crucial for the existence of human race. In the domestication of
      tobacco and pepper, manioc breads and parika, the Baniwa
      creation stories highlight this connection  

   2. The notion of obtaining things that don't belong to you is
      expressed via a Jaguar. Parika meant for shamans when consumed
      by Jaguar turns it into a gluttonous predator

   3. Use of ~Parika~ as a liminal transition trigger provides the means
      to a state where the rules of the society doesn't apply.

   4. The origin stories repeat the role of shamans and their
      ability to see the other world to reason with the unknowns in
      the current world. Specific example would be Parika and Peje
      consumption which is done in a healing ritual or elaborate
      garden ritual.

4. Are there any lessons or moral story that reflects a worldview of
   the cultural group that created the story?

   Baniwa people creation stories involves a great deal of things that
   you can still watch, observe and feel. The stories involve earthly
   objects highlighting the interconnectedness of humans and the
   ecology within which they can exist. The sustaining elements of the
   ecology are embedded in a creation story involving plants,
   predatory animals, fishing and horticulture. The importance of
   sacrifice for the greater good is also a central theme of the
   creation stories. The creation stories mention the existence of
   predatory/selfish behavior but doesn't promote any ideas of revenge
   or enacting justice via punsishment, but instead gives you reasons
   to not engage in any, which I thought was interesting. There is no
   killing involved anywhere. Just "sacrifices".
