* Apache Girl's Passage rites and Sambia Boy's Rites of Passage

1. Compare and contrast the two different rituals. How were they
   different, and how were they the same? What impact do you think
   gender has on the various aspects of the rituals? 

   The two rites were similar in that

   1. They both mark the transition from child into adolescent phase.

   2. Publicly declare the transition to the society the child is part of.

   3. Suspends the rules of the society for the child in transition

   4. The rites appear to have voluntary involvement of the
      child/parent but the ritual's appeal for "acceptance in the
      society" seem to brew group think.

   5. Child is put under new rules during the period of transition
      which indicate cleansing, prepare them for the stages in life
      the society *expects* them to go through(child bearing etc.,)

   6. Both rituals embody the community's knowledge on human biology and
      understanding of what troubles the child is expected to go
      through in their life and attempts to provide some shield from
      it, which appears to be done out of care and can feel nice in
      the right context

   7. Dance and drums

   The two rites were different in that

   1. The Apache Girl's passage rites was done to prepare the girl for
      the phases in life she is expected go through and thereby instilling values
      the society cares for. Sambia boy's rites of passage video clip
      seemed to be done out of concern for the boy's future health.
      There was a belief that he is less immune and had to be prepared
      for the physical toil he is expected go through.

   2. I can't help but feel the rites for the girl child was done with
      compassion, to the point of celebrating the girl child and
      making her feel special. With the Sambia's boy's rites, one
      leaves with the impression that the boys were scared. I want to
      cite the testimony in the video of an adult that he cried when
      it was done to him

   3. Insistence for stoic emotion, lonely living, and celebration of
      the transition with dance in the apache rite stood in
      contrast with displays of crying boys, looking scared, on the
      shoulders of their father or an elder, looking uncertain

   Gender aspect played a part in the more compassionate approach to
   immediate physical pain in the girls rites of passage as it
   appeared to focus on long periods of mental stoicness and endurance
   to prolonged physical toil in the form of dance. The instillment of
   social values(child bearing) in the rituals was present more in the
   girl's ritual than the boy's one.

2. Describe the different symbols that you observed on display during
   the ritual.

   1. The dress worn by the girls who were going through the
      passage were a symbol of being enrolled in the rites of passage

   2. The tipi setup in the girls rites of passage

   3. At the end of the rites of passage, the person offering the
      blessings had a symbol on their palm

   4. Blowing of the flutes

   5. Stinging plants

   6. Swallowing leaves

   7. Red juices of plants

3. What were the different phases of the rituals that you observed in
   the two different initiation rites, and when did they happen?
   (Identify where you saw separation, transition, reincorporation) 
   
   Separation happened when the child is taken away from their parents
   and initiated into the ritual marked by wearing clothes, and made
   to live in isolation with other children who are part of the
   ritual. This happens in both rituals. The girl child is initiated
   into the ritual when she wears the white gown and observes the
   rules of the ritual by maintaining stoic posture. Her freedom and
   rules of childhood were suspended. In the boy's rites, the boy
   seems to be carried by the father on their shoulder, as the
   community pats on his back on his way to the ritual place.
   Transition phase can be observed when the tipi was erect and the
   girls dance for hours inside the tipi. The transition phase,
   involves beating the kid with stinging plants, giving them the
   leaves to enrich their masculinity, giving them the clothes of an
   adult man to wear for the first time and passing them the secret of
   manhood. Reincorporation involved getting the girl child back from
   the tipi and offering them the final blessing by a recognized
   authority figure. This was evident in the man with a symbol on his
   palm offering advice at the girl's ear. In the boy's rite, after
   learning the secret of manhood, they transition to man move onto
   the next stage. The boy is incorporated back into the society where
   his next stage is to present himself to a future kid and then go
   onto marry a woman. After several days at the woods, the boy is
   reincorporated into the society with food(shown as yellow fruit in
   the video)

4. What norms and taboos do you think these rituals involved, or were
   otherwise trying to create? 

   The rituals were making sex a norm in the boy's ritual although it
   was done under the guise of health benefits. Physical toil was made
   a norm in both the rituals although one involved inflicting pain
   and the other involved endurance for long term solitary living and
   stoic emotions. The notion of existence of a secret was created and passing it
   down was made a norm in the boy's ritual. It would be a taboo to
   break it. The taboo in the girl's ritual was breaking the stoic
   stature. It would also be a taboo to break out of the tipi before
   10 hours(or until dawn). The message with tipi was to engage in
   living together regardless of the amount of toil you have to go
   through. One could argue that crying when the boys were beaten with
   stinging plants is a taboo or atleast looked down upon.
