* Rites of Passage
** Questions
   1. Are rites of passage performed for the benefit of society, the
      initiates, or both?

      Rites of passage are performed for the benefit of both the
      society an the initiates. Rites exemplify the transition between
      states for an individual(intiates) whereas the "state" is a
      social condition recognized by the society the individual is a
      part of. The society benefits by instilling its values in the
      individual and accepting the individual as part of the society
      and recognizing the person with the roles they are allowed to
      perfom. The individual or the neophyte benefits by experiencing
      the liminal period and being allowed to question or learn the
      myths/knowledge accummulated by the society over the years. We
      can see this in the example of "The Nursing Mother" emblem -
      Coshi wa ng'oma, among the Bemba of Zambia

   2. Why are initiates hidden from society while in the liminal
      state?

      Initiates are hidden from the society because during the liminal
      period they don't conform to the rules or the structure of the
      society. They are not physically invisible(not always atleast)
      but conceptually invisible because they are not in any of the
      socially recognized states of existence.

   3. Consider the American rite of passage of learning to drive.
      Identify the liminal state(s) during this rite of passage, and
      explain why.

      Liminal state is the training period where you are allowed to
      drive in the road with an "learners permit" and an L sign. The
      members of the society recognize you on the road, where the
      society has come together and formed some rules. Being in a
      transition state, people around you give you the space you need
      to learn and go around you or watch their way around you in
      general. You are not allowed to ride on certain types of roads
      and not beyond some arbitrary speed limits and at the end of the
      liminal state you get a driving license, having learned the
      wisdom of driving in the society, and get fully integrated with
      the society with the role of "responsible driver".
