* Discuss Ayahuasca for ANTH 101 class
** Critically analyze ayahuasca tourism
   - Three centers I chose to read
     - Spirit Vine in Brazil
     - (Redacted) center at Kona Hawaii
     - Arkana in Peru
   - All three centers offer luxurious accommodation in a carefully
     crafted jungle
   - None of them mentioned the actual money they would extract to
     offer this experience
   - One center(Arkana) mentioned that it installed solar panels in
     the villages around it with the money from the Ayahuasca
     experience and went so far as to say "By choosing to do your
     ayahuasca experience with us you would be helping the community
     around us". My initial reaction was that equation of solar panels
     to saving environment as opposed to giving the land to people who
     live there and letting them take care of it for purposes other
     than offering cheap tourism.
   - How many locals are involved in the Ayahuasca experience? Noone
     ever talked about that. If the Ayahuasca experience is all open
     to tourists but not accessible to the local people then it's
     natural to question the authenticity of the operation. The local
     people who live there also has problems and might need spiritual
     awakening. I didn't see any mention of that.
   - Singing and Dancing was mentioned.
   - Yoga was mentioned
   - Singing Icaros was mentioned in one center
   - The center in Hawaii spent a lot of time distinguishing them from
     the South American counterparts. It went so far as to say "Why go
     to South America when you can get all the benefits in here and
     hawaii is much more convenient and luxurious" or something to
     that effect which felt particularly offputting.
   - The center in Hawaii had a reviewer who accussed them of
     misconduct and the center filed a dispute with AyaAdvisors. The
     AyaAdvisors responded saying that the center's claims were false.
     The review section was interesting with court complaints. 
   - People who went through the exeperience all asked that you
     suspend the rational part of your brain that has developed over
     years of social conditioning to experience the spiritual
     awakening. This was particularly interesting because none of the
     centers mentioned it in their "Why you should choose us for
     Ayahuasca session" section.
