* Trance and Dance

1. Compare and contrast each film. How were the religious practices of
   the two different groups similar? How were they different? Talk
   specifically about the trance states and the other rituals you
   observed.

   - Similarities
     - Both involved music and dancing to enter the trance state.

     - Both were performed based on the premise that the altered
       mental state can be achieved if they forgo their rational
       reasoning and believe/surrender themselves to God.

     - Both were performed in a group.

     - Both had a leader - dictating/facilitating the enterance to
       trance state.

   - Differences
     - The Bali people trance state bordered along self harm. Whereas
       the self harm in the Holy ghost ritual seemed optional/not part
       of the trance state

     - Bali people ritual had clearly marked stages and a coherent
       story, whereas the Holy Ghost trance ritual was purely based on
       belief, facilitator and group dynamics/peer pressure.

     - Participation of children was more seen in the Bali ritual.
       They had a clear role to play.

     - No specific costumes were needed in the Holy Ghost trance dance.

     - Holy Ghost trance ritual seemed to insist that they indulge in
       the trance to rid their problems, whereas the Bali video seemed
       to imply that this trance dance ritual was periodic, cyclical
       and always present.

   - Can individuals ever achieve trance in isolation when no one is
     watching? Both relied strongly on strong group dynamics. The
     snake handling and krissing of their chest were the rituals that
     stood out the most.

2. For each film, describe an interesting topic, theme, image, symbol,
   or scene that stood out most to you, and explain why:

   In the Bali film, the scene that stood out was the old woman who
   Mead described as the one who had said that she wouldn't go to
   trance state but did. Her husband while giving her company during
   her extended trance state seemed very supportive while also keeping
   a calm, unbothered face. The Holy Ghost people video had a woman
   who spoke at length in the beginning of the video who twisted her
   neck a lot while speaking. That was freaky. She seemed to be
   slowly and consciously entering a state that was outside normal
   while describing the Holy Ghost experience.

3. Do you think that either of the trance dances you witnessed could
   be considered a form of therapy ritual or spiritual healing? Why or
   why not. 

   I didn't see too many differences between the trance dances. Being
   an outsider with an etic perspective, I feel unrelatable to the
   idea that it could be spiritual healing. I can imagine altered
   states where you forget your problems and act like your free from
   the harsh realities momentarily. But coming back from the trance
   the problems are still there. The "healing" feels momentary and
   transient. It's fine to accept temporary healing like taking a
   tablet but the spiritual healing is different from physical healing
   in that it's not materialistic. Spiritual healing doesn't happen in
   temporary altered states as the healing often requires a change. A
   change in perspective, a change in behavior, a change in
   relationship with a person/entity. The change is not temporary.
   It's hard for me to make the connection that the temporary trance
   state can lead to a spiritual healing as the trance state is
   momentary whereas spiritual healing doesn't appear to be momentary.

