* What is ritual healing theory?
  Ritual healing theory states that people with lower cognitive
  barrier between conscious state of mind and altered states of
  consciousness and thereby more likely to respond to hynosis and
  healing rituals. As a result of this, there is an evolutionary
  selection process that occured thousands of years which favored
  people who were more likely to believe in spirits, souls and altered
  states of consciousness resulting in human proclivity towards
  religious beliefs
* What is meant by shamanic performance, and how does it relate to healing?
  Shamanic performance, touted as the precursor to organized religion,
  and the earliest recognized spritual performance, involves entering
  a state of trance using hypnotic processes, demonstrating resistance
  to heat and pain, and effecting cures on people. Those are more
  susceptible to hypnosis are more likely to be shamans and the cures
  they effect on others appear to work on people who are prone to
  altered states of consciousness, incited usually via rituals. This
  altered state of consciousness is believed to have physiological
  effects that helps with healing some illnesses.  
