* Healing Rituals
1. While you were reading the article, "Body Ritual among the
   Nacirema," did you recognize anything familiar about their culture?
   Did you suspect anything was off? Or were you totally surprised by
   the revelation that it was satire? Explain. Full disclosure: I
   totally fell for it the first time I read it, and that was in grad
   school!

   Interesting. I did not recognize that something was off until I
   read this question. I read the article on Tuesday before class and
   just now came to the realization that it was satire. Great April
   fools material for next year that I may use on others. When I
   reread it, I picked up on his satire with the painful realization
   that the work on realigning perspectives and not having biases
   while hearing/watching something that is different from what I'm
   used to. Why are we that way though? Why did we evolve to compare
   our own experiences/perspectives to form judgments.

2. After reading the article "Psychogenic Death: Individual Effects of
   Sorcery and Taboo Violation,"  do you think psychogenic death might
   be a form of mental illness? Why or why not?

   The article didn't make me feel like Psychogenic death was a form
   of mental illness. What constitutes mental illness is deviation
   from the norm. Is the person refusing to accept their beliefs on
   being given rational evidence? In the case of the boy who thought
   his cousin was out to get him, what possible rational evidence
   could anybody bring to him that would make him reconsider that his
   belief was misguided? The event happened between him and his
   cousin. Noone else was there. So, to rationally update his belief
   he would have had to hear from his cousin or believe that there is
   a medicine to reverse the curse. Asking him to believe that his
   cousin had never made the curse wasn't going to work because noone
   except the cousin can answer it. Convincing him that his cousin's
   curses aren't effective is flawed because that goes against the
   boy's belief system on religion and magic. It would take a lot of
   effort to change that belief system. To assess mental illness, one
   must first understand their existing belief system and give them
   rational evidence to see if they are open to updating their mental
   model. In both the cases that we read there wasn't enough evidence
   to show that the people involved were understood first and then
   presented rational evidence to update their beliefs. So, I didn't
   feel like they were mentally ill.

