* Divination Exploration

1. What magical practices or divination techniques have you, your
   friends, or your family experienced in your lifetime (for example,
   have you ever read your horoscope? Do you know your astrological
   sign? Do you have an object or ritual that brings you luck? Have
   you ever had your tarot cards read? Etc.) Describe the experience.

   My grandfather was very interested in astrology and practiced sign
   reading/horoscope as part-time work. Since my grandparents lived
   with us, he would occasionally get visitors to get their horoscope
   read. Funnily enough, my grandmother was always critical of his
   reading and used to say that he should try to put a positive spin
   on the readings rather than always being negative. He had
   horoscopes written for all of us but would never read it to us. He
   would write it and leave it, and I never got to read mine. The town
   I grew up in had a lot of people who believed in horoscopes. We
   were told that our town was the birthplace of
   https://www.astroved.com/nadi/nadi-astrology . There's still quite
   a lot of people who believe in this and visit our town to get their
   nadi leaf read to them. Ironically, I never got this read to me as
   well. Because of the increased belief in horoscopes in the region I
   grew up, there were a lot of people who were into this profession -
   either casually or seriously. My grandfather was also quite good at
   spotting charlatans. I remember a time when we invited a nadi leaf
   reader to our house to read my dad's palms, and the horoscope
   reader, in order to impress us, tried to make a doll that he
   brought with us move. He did make the doll move on its own, and some of us
   were surprised, but my grandfather stopped him abruptly as soon as
   he did that and said he knows what he is doing and thanked him for
   his services and let him on its way. I can't remember a time I had
   a divination experience happen to me but I always hear from people
   around me.


2. Did the divination practice have the desired effect and/or was it
   accurate? Were you surprised at the outcome?

   Not really. My mom believes in horoscopes and has horoscopes read
   for the entire family(good luck, arguing about consent), and tells
   us about it. I have never had a moment where I felt that
   anything has worked for me, and even she agrees that it doesn't
   work for her but still keeps going. My impression from all the
   efforts was that the readings were vague enough to be associated
   with a multitude of random events in your life. They would usually
   be like "Your son will live away from you and can't reach you
   easily". The first half of the sentence is true for most people,
   and the second half is so subjective. Precision is hard to get but
   is unfortunately expected to tilt someone's beliefs towards another way.


3. In your opinion, what is it about divination techniques that
   continues to attract people, even if they are not otherwise
   religious and/or spiritual? 

   Divination techniques has an element of thrill, it fulfills that
   hope towards something happening out of your rational expectations.
   Losing someone close to you or wanting something you can't have,
   are situations that the rational part of the mind finds it hard to
   accept. So, any comfort during these uncertain situations, is a strong
   inclination towards divination. Reality is mundane and boring. Our
   brain enjoys out of the ordinary things and fills us with fresh
   hope and beliefs, that rationality finds so hard to derive.
