* Topic: Cult

1. In your opinion, what was the main takeaway or lesson of the
   podcast?

   Trouble childhood seems to be a common pattern in making oneself
   long for answers and conceive frameworks to get them. In the case
   of Rajneesh, it was the loss of grandparents and for Charles Manson
   his troubled mom and jail life. It seemed like both of them were
   made to look for answers within to fill a void left by others. It
   doesn't justify anything they did but it's interesting that this
   self search resulted in beliefs that they can convince others,
   influence them and achieve greatness. With
   the knowledge of some self-help tricks, he managed to influence a
   lot of people. Beatles like fame constituted greatness and gave him
   something to aspire to. 
   
2. What role do you think the 1960's hippie and new age movements
   played in Manson's ability to convince women and men that he was a
   spiritual leader? 

   New age and hippie movements played a significant role as per the
   podcaster. The podcaster says "They young adults were not activists
   so much as escapists". Young people who resisted parents or people
   who felt they were made to follow suit and not show any dissent
   ,identified as the hippies of Haight-Ashbury, were the ones who
   were the easy targets for Charles Mason's recruits. The podcast
   talks about the way people dress up to question conventional
   straight way of existing in society. By validating their rejection
   of the norms, Mason entered their mind and his post-modern moral
   relativist philosophy completed the rest. It worked on this people
   because, as the podcaster notes, these people were searching for
   alternate models of thought

3. Do you think a figure like Manson would be able to convince people
   to follow him and join his cult today? Why or why not? 

   I don't think much has changed between his time and now. Have
   people become less convinced moral relativism? I don't think so. Do
   young people still feel their dissenting voice doesn't have a place
   in the room? Yes. Do people seek out validation for their
   dissenting voice or beliefs in others, and feel attached to the one
   who give them? The only difference between now and then is the
   awareness of manipulation techniques among today's youth.
   Hopefully, more people recognize that alienating someone from their
   friends and family by withholding validation or anything the person
   needs is a form of abuse. If anything, my only hope is on the
   awareness of the forms of abuse among young people.
