* Devil and saints in the conquest of Mexico

1. In what ways did demonizing Aztec gods facilitate colonization?
   
   - Demonizing Aztec gods resulted in questioning monism and pushed
     towards accepting the dualism of Christainity. Once you make
     people question their way of life, there's naturally an interest
     in the alternate choice provided. When an interest develops, you
     have the floor to create illustrations to present your ideologies
     and pave ways for acceptance - Colonization 
     
   - "The psychological need" presented by the author, as surprising
     as it sounds, could have fueled colonization, if true. The
     reasons for this need, as presented by the author, were turbulent
     conditions of the nature, which was filled with spirits that
     existed on a degree. The dualistic presentation of good vs evil
     being the cause of chaotic life conditions, and the option to
     always choose the good spirit side over the evil, influenced
     curiosity, and the demonization of any rituals to appease the
     devils of Aztec gods 

2. Could Aztec's interests in/acceptance of the devil function as a
   form of resistance to oppression? Why or why not? 

   As per the author, it doesn't seem so. The one example, the author
   provided was that of a man who had started practicing christianity
   religiously and had a dream where the devil told him that it needs
   the sacrifice in the church. So, the author refuses to affiliate
   this action or similar instances of interfusion of devil worships
   with christianity an action of resistance to oppression. However
   the author also points out that the Friars, on the other hand, felt
   that they had to give in to interfusion of mesoamerican gods with
   christianity in order to further the spread of their ideologies.
   So, clearly they felt a threat to their intention of spreading
   christianity onto others. If they could have, they would have

3. Why do you think Santa Muerte is becoming more and more popular
   among certain groups in Mexico?

   Santa Muerte appeals to the monistic perception of the
   supernatural. It can be a demon or symbol of death that needs to
   beb appeased or a feminine caring figure which should not wronged.
   The authors claim that Mexicans confront death on a daily basis in
   their way of life. So, having Santa Muerte as a symbol of death and
   confronting it, having it in their mind, helps with accepting death
   as a part of life and not as something that is to be dreaded so
   much that you lose the present in fear.

4. Do you think Santa Muerte has been demonized by people with an etic
   perspective of her? Why or why not?

   I think so. Etic perspective from a person who is not familiar with
   monism or understanding of Mexican culture is more likely to look
   at the figure of Santa Muerte and associate it with their
   understanding of skull heads - demons. Santa Muerte is a result of
   syncretism. So, studying it from an etic perspective is always to
   doomed to get one perspective. Syncretism evolves over time and the
   ideologies associated with it lives among people in the society.
   So, an etic perspective is not likely to get a full picture of
   Santa Muerte.
