* Korean Shamanism
  1. In your opinion, what was the main takeaway or lesson of the
     film?
     
     My main takeaway from the film was that Korean culture shamanistic
     rituals are a reflection of the Korean society. Belief in
     shamanism is part of everyone's life, and it's not just a
     religion of the oppressed or the working class. Koreans with
     stable and unstable lives indulge in shamanistic beliefs to
     retain their position in the society or further their position in
     the society. There's a marked change in the objective of these
     shamanistic rituals that reflect the worries/uncertainties that
     Koreans have in their daily life. The objective of these rituals
     changed from health and giving right send off to ancestors to
     save oneself from the volatile nature of the society. The film
     highlighted the rituals that shamans perform for a variety of
     evolving needs that Koreans have and is an example of how
     religious beliefs exhibited by humans is a mirror into the
     society that they live in. 

  2. Describe an interesting topic, theme, image, symbol, or scene
     that stood out most to you, and explain why:

     What stood out the most to me from the film was the use of drums.
     Throughout the movie, there was drums and dance involved, and the
     shamans wore clothes that were mostly white. I don't remember the
     film explaining the significance of the color or the dance but
     the use of drums to summon God and invite it to play it with
     drumstick as part of the exorcist ritual was interesting as to
     why drums? why not any other musical instrument? Does drums in
     anyway have more religious significance than other musical
     instrument? Drums are one of the oldest instruments that most
     culture have some form of association with it but the
     significance of music and especially drums was interesting. The
     music they played in the film sounded very familiar to what
     Hawaiians play during Luaus for tourists on expensive lawns in
     the evening. The pig head was also giving me semblances of
     Hawaiian culture.

  3. What were the main rituals the shaman performed in the film?
     Compare these rituals to the rituals you read about in the Sacred
     Realms chapter “Korean Shamans and the Spirits of Capitalism”
     (page 132). 

     Rituals performed in the film:
     - sea goddess(guardian angel) offered phallic symbols to protect the village from trouble

     - Individuals and group offered prayers to the guardian

     - Exorcists pass on the will of God to people and viceversa

     - Healing rituals

     - Exorcism ritual as healing for the entire village had the
       entire village participate in it.

     - Child's birth - three gods of birth

     - After 7th year, seven star god - exorcist becomes child's
       foster mother(!?)

     - Bride and Groom cleansed before entering the house.

     - Washing exorcism - calm the soul of the dead by cleansing it

     - Ease the grievances of the dead by untying the seven knots

     The rituals mentioned in the book are an indication of the marked
     change in the objective of the rituals. Rituals were performed
     related to individual wealth rather than achieving collective
     prosperity as in the case of the guardian angel ritual or healing
     ritual for the village. The objective of the rituals become
     materialistic in nature as evidenced by the request to further
     their business fortunes and the request for million Korean money.
     The book also mentions some rituals had the language of material
     interests but were also performed for healing of health
     concerns(in the case of leg pain). There were rituals performed
     when "any new goods" were brought into the house or when someone
     buys a new house. The book also talks about how there is little
     ritual in appeasing the ancestors reflecting the concerns of the
     industralized Korean society 
