* Religious Specialist
#+BEGIN_SRC 
Imagine you were a religious specialist. Based on what you have
learned about religious specialists, which religious specialization
would you choose for yourself (or grudgingly tolerate, if that is more
realistic for you)? From what you know, which kind of religious
practitioner sounds the most appealing to you, and why? Explain what
your role would be in your society, and what rituals you might imagine
you would be leading. Feel free to have fun with this, and be as
imaginative as you like. But remember, you need to choose one of the
specialists we learned about in class (in other words, you can't be
Harry Potter, sorry).
#+END_SRC
I think I'd chose the option of an avatar since you have the
power be a reincarnation that the society needs. A more useful
reincarnation during these times would be a wealth destroyer who has
the power to make people's wealth disappear and make that person
insignificant and unrecognizable to anyone is the reincarnation power
I want to have in my avatar. The idea of living
among people and being able to see them function, and viceversa, but
nobobdy recognizes what you say or knows who you are, and becoming
insignificant overnight for reasons you can't understand is what I'd
wish to happen to them. The society can approach the avatar when they
realize they someone has exploited others and made a fortune, and the
avatar can wield it's power to provide justice. So, what's your list?
and why does it start with Bezos? The avatar will have the face
and claws of a lion when it gets angry, like the hulk, but when it's
normal it can be a sea otter.
