* Assignment 8

1. What theme, lesson, or scene from the film had the most impact on
   you?

   Oppression of women. Undoubtedly, that's the most impactful message
   from the film. It also shows how detrimental and short-sighted
   religion can be. As long as we have unknowns in the world,
   religions will exist. But when a religion is misguided or refuses
   to adapt to the needs of the society or the evolving minds of
   humans, it can be quite cruel to the members of the society it
   doesn't include or marginalizes. The scene where they showcase the
   different tools used for inquisition and punishment was an
   impactful scene. It's horrendous that the scientific discoveries
   were used, and even fueled by, the need to oppress people. Any
   scientist/intellectual without an interest to learn their social
   responsibilities and claiming "doing just their job" has to bare
   the blame here. I have always wanted to see a girl child grow and
   become the powerful being she can be, and this film made that wish
   even more conrete. There's a very simple way to empower women. Stop
   oppressing them. Nobody needs your help in climbing up. They just
   don't want to be pulled down by you.

2. What do you think were the main reason(s) or motivation(s) for the
   filmmakers in making this film?

   1. Take down the negative stereotypes against religion(s)/practices that empower
      women.

   2. Highlight the oppression of women by patriachical or
      monotheistic religions that doesn't treat them as normal but as
      embodiment of unknowns/devils

   3. Bring a change into the society that acknowledges the problems
      with popular religions, especially Christianity, and make room
      for women without discriminizing against them

      The scenes that highlight these are the ones where they narrate
      that around 9 million women where killed over 300 years under
      the name of witchcraft. All these women did were practice
      healing. Accusing midwives who were relieving pain during births
      as going against God's will is one of the stupidest things I
      have ever heard and it should make every reasonable human being
      angry. It also shows how dumb and cruel religions can be when
      they don't include you.
  
3. Compare and contrast the main ideas of the film to the reading from
   Sacred Realms chapter “The Goddess and Power: Witchcraft and
   Religion in America” (page 398). What impacts do you think the
   legacy of the witch hunts have on people who practice Wicca today?

   1. The main ideas of the film and the paper were different in that
      the film focussed on highlighting the negative stereotypes against
      women who practiced witchcraft whereas the article was more about
      why women seek out and practice a religion that empowers them.

   2. The paper and the movie were similar in highlighting the
      negative stereotypes that comes with witchcraft or witches

   3. The paper addresses the sociologists concern with religions and
      how Wicca overcomes them by "remythollgizing" and keeping it's
      values grounded to everyday life and simple.

   4. Authors of the paper claim that Consequence/Responsibility
      drives morality and one's actions as opposed to other worldly
      sin/blessings in Wicca. The movie is not limited to Wicca but
      mentions in passing that women witches to this day practice acts
      to feel the empowerment, although not in open public, because of
      centuries of negative stereotypes.

   5. Impacts: Cast as an outsider, Not considered normal, removal of
      moral agency on their words, called delusional, irrational

4. Witchcraft and Wicca are slowly but surely being more openly
   represented in pop culture and the media. However, as the Shannon
   Barber articlePreview the document noted, only certain types of
   witchcraft seem to be socially acceptable. How do you think Amanda
   Yate Garcia may have been treated differently by the Fox News
   Anchor if she weren't
   white/cisgendered/femme/thin/able-bodied/young, etc.?

   If AYG weren't all those, then I imagine a dark looming background
   with symbols of witches or ominous music backgrounds being played.
   I can imagine some misogynist references to witches being prefaced
   in the questions aimed at her. It's possible that the TV host could
   have padded up the segment with an opposing voice from a prominent
   scientist/researcher who calls her psychotic while the TV host
   plays neutral. All you need is one opposing view for the TV
   channels to play neutral and not take any responsibility. I can
   imagine the TV host highlighting some of the books she had written
   and claim that "this is the work of the leftists that the children of
   this country are reading" in a looming voice crying portraying it
   as close to end of the world. And perhaps, call her a "communist"
   or a member of the opposition party?
  
